# azure-pipelines.yml | San Marcos GIS on Azure
#
# Copyright (C) 2023 City of San Marcos CA
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
  #pool:
  #  name: 'On-Premises'

variables:
  #ServiceConnectionName: 'GISTestServiceConnection2'
  #EnvironmentType: 'nonprod'
  #ResourceGroupName: 'rg-cosm-gis-env-test'
  DeploymentDefaultLocation: 'westus'
  System.Debug: true
  #SubscriptionId: '66d233df-ad0c-45a4-a6bc-d77919e18237'

stages:
  - stage: deployStage
    jobs:
      - job: Deploy
        steps:
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: $(SubscriptionId)
              action: 'Create Or Update Resource Group' # 'Create Or Update Resource Group' | 'Select Resource Group' | 'Start' | 'Stop' | 'StopWithDeallocate' | 'Restart' | 'Delete' | 'DeleteRG'. Required. Action. Default: Create Or Update Resource Group.
              resourceGroupName: $(ResourceGroupName)
              location: $(DeploymentDefaultLocation)
              templateLocation: 'Linked artifact' # 'Linked artifact' | 'URL of the file'. Required. Template location. Default: Linked artifact.
              deploymentMode: 'Incremental' # 'Incremental' | 'Complete' | 'Validation'. Required. Deployment mode. Default: Incremental.

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              subscriptionId: $(SubscriptionId)
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)
              csmFile: main.bicep
              deploymentMode: 'Complete'
              overrideParameters: >
                -location "$(DeploymentDefaultLocation)" 
                -environmentType "$(EnvironmentType)" 
                -networkConnectionSharedKey '$(networkConnectionSharedKey)'